name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        types: [opened, synchronize]
        
jobs:
    build:
        name: Build & test
        timeout-minutes: 15
        runs-on: ubuntu-latest

        steps:
            - name: Check & code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: pnpm/action-setup@v3
              with:
                version: 8
                
            - name: Setup Node.js env
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'pnpm'

            - name: Install deps
              run: pnpm install

            - name: Build
              run: pnpm -r run build
            
            - name: Test
              run: pnpm test 
